- Id: d87fe4cd-d172-4d5f-8d5a-14082724b641
  Name: otk
  Weight: 50
  Enable: true
  Tag:
  - otk
- Id: bf198e67-a4b4-477b-859a-83192adc5eb2
  Name: 站立弯腰
  Weight: 50
  Enable: true
  Tag:
  - sp
- Id: 4f0faea9-e386-4e8d-8276-306a8fc2c14d
  Name: 尿布式
  Weight: 50
  Enable: true
  Tag:
  - sp
  - diy
- Id: cd065fc4-e2a4-4158-92e5-f76b1c4dc707
  Name: 跪趴
  Weight: 50
  Enable: true
  Tag:
  - sp
  - diy
- Id: bc31df3a-1b03-44a7-bd27-642b8e2d21ad
  Name: 扶墙站立
  Weight: 50
  Enable: true
  Tag:
  - sp
- Id: ee849648-3201-49b9-8b15-df63fab2bf57
  Name: 趴床
  Weight: 50
  Enable: true
  Tag:
  - sp
- Id: 5f9e7776-ae56-4e43-bfa3-67a5ccef9bdc
  Name: 手扶桌子
  Weight: 50
  Enable: true
  Tag:
  - sp
- Id: 1ac4a444-d46b-4c25-87dd-814fb2de40bf
  Name: 膝上
  Weight: 50
  Enable: true
  Tag:
  - otk
- Id: 4f566f24-7241-4f9e-801f-89965c0d354c
  Name: 平趴膝上
  Weight: 50
  Enable: true
  Tag:
  - otk